-- return {
--   "nvim-lualine/lualine.nvim",
--   dependencies = { "nvim-tree/nvim-web-devicons" },
--   config = function()
--     local lualine = require "lualine"
--     local lazy_status = require "lazy.status" -- to configure lazy pending updates count
--
--     -- configure lualine with modified theme
--     lualine.setup {
--       options = {
--         theme = "ayu_dark",
--       },
--       sections = {
--         lualine_a = { "filename" },
--         lualine_b = { "branch" },
--         lualine_c = { "branch" },
--         lualine_x = {
--           {
--             lazy_status.updates,
--             cond = lazy_status.has_updates,
--             color = { fg = "#ff9e64" },
--           },
--         },
--         lualine_y = { "filetype" },
--         lualine_z = { "" },
--       },
--     }
--   end,
-- }
-- return {}
return {}
