import = [
    "~/.config/alacritty/themes/themes/alacritty_0_12.toml"
]

# [env]
# TERM = "xterm-256color"


[window]  
padding.x = 10
padding.y = 10

decorations = "Buttonless"
# opacity = 0.8
option_as_alt = "Both"


[font]
normal = {family = "BitstromWera Nerd Font Mono", style = "Regular"}
italic = { family = "BitstromWera Nerd Font Mono", style = "Oblique" }
bold = { family = "BitstromWera Nerd Font Mono", style = "Bold" }
# offset = { x = 0, y = -1 }
size = 18



