import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"
]

# [env]
# TERM = "xterm-256color"


[window]  
padding.x = 10
padding.y = 10

decorations = "Buttonless"
# opacity = 0.8
option_as_alt = "Both"

[font]
normal = {family = "MesloLGS Nerd Font Mono", style = "Regular"}
offset = {x = 0, y = -2}
size = 17.3
